Mygcpsteps
artvalborgcp/getting-started-python pull request #2
Opened 2021-06-13 19:59 UTC by artvalborgcp

Create and destroy infrastructure with terraform

2021-06-14 17:35 UTC, yevheniimykhailin requested changes

2021-06-14 17:35 UTC, yevheniimykhailin commented on 7-gce/bookshelf/tasks.py
> +from google.cloud import pubsub_v1
from google.cloud import pubsub_v1 as pubsub

2021-06-14 17:35 UTC, yevheniimykhailin commented on 7-gce/config.py
> +PROJECT_ID = 'my-gcp-terraform'
import os

PROJECT_ID = os.environ.get(PROJECT_ID, 'my-gcp-terraform')

you can pass via env vars

2021-06-14 17:35 UTC, yevheniimykhailin commented on 7-gce/config.py
> +CLOUDSQL_CONNECTION_NAME = 'my-gcp-terraform:us-central1:bookshelf'
same here

2021-06-14 17:35 UTC, yevheniimykhailin commented on 7-gce/config.py
> +CLOUD_STORAGE_BUCKET = 'my-gcp-terraform-bucket'
same here

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/instance.tf
> +*/
remove if not needed

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/instance.tf
> +  unhealthy_threshold = 10 # 50 seconds
as variables with default values

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/mynetwork.tf
> +  count   = "1"
Why do you put count=1?

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/outputs.tf
> +
Add more outputs

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/sql.tf
> +
add labels

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/sql.tf
> +    tier = "db-f1-micro"
as variable

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/sql.tf
> +  region = "us-central1"
as variable

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/sql.tf
> +      ipv4_enabled    = true
external IP?

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/variables.tf
> +  description = "Port the service is listening on."
add type

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/variables.tf
> +}
add type

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/variables.tf
> +  default     = ""
add type

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/variables.tf
> +  default     = "true"
should be bool with true without ""

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/variables.tf
> +  default     = "10"
should be number with just 10

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/variables.tf
> +  default     = "false"
bool

2021-06-14 17:35 UTC, yevheniimykhailin commented on terraform/variables.tf
> +  default     = "pd-standard"
type

2021-06-28 11:36 UTC, artvalborgcp commented on 7-gce/config.py
> +PROJECT_ID = 'my-gcp-terraform'
fixed

2021-06-28 11:36 UTC, artvalborgcp commented on 7-gce/config.py
> +CLOUD_STORAGE_BUCKET = 'my-gcp-terraform-bucket'
fixed

2021-06-28 11:36 UTC, artvalborgcp commented on terraform/instance.tf
> +*/
removed

2021-06-28 11:36 UTC, artvalborgcp commented on terraform/instance.tf
> +  unhealthy_threshold = 10 # 50 seconds
complete

2021-06-28 11:36 UTC, artvalborgcp commented on terraform/mynetwork.tf
> +  count   = "1"
deleted

2021-06-28 11:36 UTC, artvalborgcp commented on terraform/variables.tf
> +  default     = "10"
made

2021-06-28 11:36 UTC, artvalborgcp commented on terraform/variables.tf
> +  default     = "false"
made

2021-06-28 11:36 UTC, artvalborgcp commented on terraform/variables.tf
> +  default     = "pd-standard"
done

2021-06-28 11:36 UTC, artvalborgcp commented on terraform/variables.tf
> +  default     = "true"
added

2021-06-28 11:36 UTC, artvalborgcp commented on terraform/variables.tf
> +  default     = ""
added

2021-06-28 11:36 UTC, artvalborgcp commented on terraform/variables.tf
> +  description = "Port the service is listening on."
added

2021-06-28 11:36 UTC, artvalborgcp commented on terraform/variables.tf
> +}
added

2021-06-30 07:03 UTC, yevheniimykhailin requested changes
All looks good, there are some tiny things to fix but all good.
Next PR should have modules.

2021-06-30 07:03 UTC, yevheniimykhailin commented on terraform/outputs.tf
> +output "google_sql_database_instance_id" {
add description

2021-06-30 07:03 UTC, yevheniimykhailin commented on terraform/outputs.tf
> +output "google_sql_database_instance_ip" {
add decription

2021-06-30 07:03 UTC, yevheniimykhailin commented on terraform/mynetwork.tf
> +resource "google_service_account" "isa" {
should it go to iam.tf? if you split files - try to keep elements logically isolated.

2021-06-30 07:03 UTC, yevheniimykhailin commented on 7-gce/config.py
> +DATA_BACKEND = os.environ.get('DATA_BACKEND')
os.environ.get('DATA_BACKEND', SOME_DEFAULT_VALUE)
the same below

2021-06-30 07:03 UTC, yevheniimykhailin commented on 7-gce/bookshelf/tasks.py
> +from google.cloud import pubsub_v1
did you address that comment ^?

2021-06-30 07:03 UTC, yevheniimykhailin commented on 7-gce/gce/startup-script.sh
> +
remove some blank lines

2021-07-05 07:54 UTC, artvalborgcp commented on 7-gce/bookshelf/tasks.py
> +from google.cloud import pubsub_v1
fixed

2021-07-05 07:54 UTC, artvalborgcp commented on 7-gce/config.py
> +CLOUDSQL_CONNECTION_NAME = 'my-gcp-terraform:us-central1:bookshelf'
fixed

2021-07-05 07:54 UTC, artvalborgcp commented on terraform/outputs.tf
> +
added

2021-07-05 07:54 UTC, artvalborgcp commented on terraform/sql.tf
> +    tier = "db-f1-micro"
made

2021-07-05 07:55 UTC, artvalborgcp commented on terraform/sql.tf
> +  region = "us-central1"
made

2021-07-05 07:55 UTC, artvalborgcp commented on terraform/outputs.tf
> +output "google_sql_database_instance_id" {
added

2021-07-05 07:55 UTC, artvalborgcp commented on terraform/outputs.tf
> +output "google_sql_database_instance_ip" {
added

2021-07-05 07:56 UTC, merged